name: 'Setup Quarkdown'
description: 'Set up Quarkdown CLI for GitHub Actions'
author: 'Quarkdown'

branding:
  icon: 'file-text'
  color: 'green'

inputs:
  quarkdown-version:
    description: 'The version of Quarkdown to install (e.g., "1.0.0"). If not specified, installs the latest version.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Quarkdown
      shell: bash
      run: |
        INSTALL_DIR="$RUNNER_TOOL_CACHE/quarkdown"
        INSTALL_ARGS="--prefix $INSTALL_DIR"
        
        if [ -n "${{ inputs.quarkdown-version }}" ]; then
          if [ "${{ inputs.quarkdown-version }}" = "devbuild" ]; then
            INSTALL_ARGS="$INSTALL_ARGS --tag latest"
          else
            INSTALL_ARGS="$INSTALL_ARGS --tag v${{ inputs.quarkdown-version }}"
          fi
        fi
        
        curl -fsSL https://raw.githubusercontent.com/quarkdown-labs/get-quarkdown/refs/heads/main/install.sh | bash -s -- $INSTALL_ARGS
        echo "/usr/local/bin" >> $GITHUB_PATH

    - name: Verify installation
      shell: bash
      run: quarkdown --version
